server:
  port: 9003
spring:
  application:
    name: leadnews-wemedia
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews_wemedia?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 12345678
  cloud:
    nacos:
      server-addr: 192.168.173.131:8848
  redis:
    host: 192.168.173.131
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  #mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  #type-aliases-package: com.heima.model.user.pojos
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql日志
seata:
  application-id: ${spring.application.name}
  enabled: true
  service:
    disable-global-transaction: false
    grouplist:
      default: localhost:8091
    vgroup-mapping:
      my_test_tx_group: default
  tx-service-group: my_test_tx_group
minio:
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: leadnews
  endpoint: http://localhost:9000
  readPath: http://localhost:9000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
